#ifndef DEFINITIONS_H_
#define DEFINITIONS_H_

#define CLIENT_ADDRESS 0x00
#define SERVER_ADDRESS 0x01
#define CODE_REQUEST 0x23
#define CODE_SEND 0x16

#define SUB_CODE_REQUEST_INTERNAL_TEMPERATURE 0xC1
#define SUB_CODE_REQUEST_REF_TEMPERATURE      0xC2
#define SUB_CODE_REQUEST_USER_COMMANDS        0xC3

#define SUB_CODE_SEND_CONTROL_SIGNAL 0xD1
#define SUB_CODE_SEND_REF_SIGNAL     0xD2
#define SUB_CODE_SEND_ON_OFF         0xD3
#define SUB_CODE_SEND_WORKING_STATE  0xD5
#define SUB_CODE_SEND_TIMER          0xD6

#define USER_CMD_TURN_ON        0x01
#define USER_CMD_TURN_OFF       0x02
#define USER_CMD_START_HEATING  0x03
#define USER_CMD_CANCEL_PROCESS 0x04
#define USER_CMD_INCREASE_TIMER 0x05
#define USER_CMD_DECREASE_TIMER 0x06
#define USER_CMD_MENU           0x07

#define KP 30.0
#define KI 0.2
#define KD 400.0

#endif
